#!/bin/sh

set -euo pipefail

podman build -t mymarvin:latest .
podman run --security-opt=label="disable" --rm -it -p 8080:8080 -p 50000:50000 --env-file=.env --env-file=.env.local -v "$(pwd)/job_dsl.groovy:/var/jenkins_home/job_dsl.groovy:ro" -v "$(pwd)/my_marvin.yml:/var/jenkins_home/jenkins.yaml:ro" mymarvin:latest
