FROM jenkins/jenkins:lts-jdk17
USER root
RUN apt-get update && apt-get install --no-install-recommends -y \
        gcc \
        libc-dev \
        make \
    && rm -rf /var/lib/apt/lists/*
USER jenkins
RUN jenkins-plugin-cli --plugins cloudbees-folder configuration-as-code credentials github instance-identity job-dsl script-security structs role-strategy ws-cleanup
